version: '3.8'
services:
  casa_do_codigo_api_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: casa_do_codigo_api_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=casa_do_codigo_db
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume: